// <auto-generated />
namespace QuizApplication.Logic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class QABase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QABase));
        
        string IMigrationMetadata.Id
        {
            get { return "201912141558073_QABase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
